// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smoxbbuvuwjarpuxanmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtb3hiYnV2dXdqYXJwdXhhbm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDMzNDcsImV4cCI6MjA2ODAxOTM0N30.zppp0hJd1n8ZmdAc4w6Z5hM63jCTj7t2RHRiKEhBj-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});