name: Build and Deploy
on:
  push:
    branches: [ main ]  # Trigger on pushes to `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build  # Your build script
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'  # Replace with your build output folder

  deploy:
    needs: build  # Wait for build job to finish
    runs-on: ubuntu-latest
    environment:  # ⭐ REQUIRED FOR GITHUB PAGES ⭐
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4  # Official GitHub Pages action
