name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install vite@latest @vitejs/plugin-react@latest

      - name: Build project (with strict verification)
        run: |
          # Clean previous builds
          rm -rf dist node_modules/.vite
          
          # Run build with debug logging
          npm run build 2>&1 | tee build.log
          
          # Verify critical files exist
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Error: index.html missing!"
            exit 1
          fi
          
          if [ ! -d "dist/assets" ]; then
            echo "❌ Error: assets folder missing!"
            echo "=== Build log ==="
            cat build.log
            exit 1
          fi

          echo "✅ Build verified:"
          ls -R dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
