name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        run: npm run build

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'  # Or 'build' if using Create React App

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
