name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]

# ↓↓↓ THIS PERMISSIONS BLOCK IS CRITICAL ↓↓↓
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install
      - run: npm run build
      
      # ↓↓↓ THE KEY FIX - USING v2 NOT v3 ↓↓↓
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
